server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone_springboot
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: Sf76ODirXZoufqGtUXBgNp3uOL0i1tYvj23Xpu5EQNM=